# -*- coding: utf-8 -*-
"""bfs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJJYE4szdZE_pkSmuFMwBI-b1fOjvnZa

Breadth First Search
"""

from collections import deque

def bfs(graph, start):
    visited = set()
    queue = deque([start])
    while queue:
        node = queue.popleft()
        if node not in visited:
            print(node, end=" ")  # Visit the node
            visited.add(node)
            queue.extend(neighbor for neighbor in graph[node] if neighbor not in visited)

# Example usage
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

bfs(graph, 'A')
b