# -*- coding: utf-8 -*-
"""dfs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qN1OYzSvxgf0x9A4fECG5J2mEQSVOZwQ
"""

def dfs(graph, start, visited=None):
    if visited is None:
        visited = set()
    visited.add(start)
    print(start, end=" ")  # Visit the node
    for neighbor in graph[start]:
        if neighbor not in visited:
            dfs(graph, neighbor, visited)

# Example usage
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

dfs(graph, 'A')

