# -*- coding: utf-8 -*-
"""insertion_sort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xF2-XpMMmnlPMK3gRTGPCsjHtti-0VaD
"""

import random
import time
import matplotlib.pyplot as plt

def insertion_sort(arr):    #method sorting the data using insertion sorting algorithm
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key

def measure_time(arr):    #method for measuring time taken for the process each time
  start = time.time()
  insertion_sort(arr)
  end = time.time()
  return end - start

data_sizes = [1000, 2000, 3000, 4000, 5000]   #different data sizes for each iteration
times = []

for size in data_sizes:
  arr = [random.randint(1, 10000) for _ in range(size)]    #generating n(data) random numbers between 1 - 10000
  time_taken = measure_time(arr)
  times.append(time_taken)

plt.plot(data_sizes, times, marker='o')
plt.xlabel('Data Size')
plt.ylabel('Time Taken')
plt.title('Insertion Sort')
plt.show()

